Add unit tests Distributions.Discrete.Hypergeometric
fslaborg/FSharp.Stats pull request #221
Opened 2022-06-24 09:24 UTC by Freymaurer

**Please list the changes introduced in this PR**

- testList "Distributions.Discrete.Hypergeometric" with 9 tests ✅ 
  - testing `hypergeoCheckParam` for edge case coverage
  - test all member functions of `Distributions.Discrete.Bernoulli` used in `Distributions.Discrete.bernoulli`
  - do all tests on different bernoulli distributions covering: min, max, default and nan.
- add verbose failure check `hypergeoCheckParam_k` + tests.
- update docs 📚 
  - add example for the Sample() function
  - Change wording to be more in line with function parameters. Should improve understandability.

**Additional contest**

⚠️ CDF still has float as input. This is missleading and should be changed in a bigger rework of the Distribution<'a,'b> interface!

**[Required]** please make sure you checked that
 - [x] The project builds without problems on your machine

**[Optional]**
 - [x] Added unit tests regarding the added features

2022-06-27 14:51 UTC, bvenn requested changes

2022-06-27 14:51 UTC, bvenn commented on src/FSharp.Stats/Distributions/Discrete.fs
>              hypergeoCheckParam N K n
Remove this line to not checking parameters twice.

2022-06-27 14:51 UTC, bvenn commented on src/FSharp.Stats/Distributions/Discrete.fs
> +            hypergeoCheckParam N K n
see above

2022-06-28 10:42 UTC, Freymaurer commented on src/FSharp.Stats/Distributions/Discrete.fs
>              hypergeoCheckParam N K n
Do you mean i should remove `hypergeoCheckParam`? Because `hypergeoCheckParam` and `hypergeoCheckParam_k` test different cases. They do not overlap.

2022-06-28 10:44 UTC, bvenn commented on src/FSharp.Stats/Distributions/Discrete.fs
>              hypergeoCheckParam N K n
Correct, sorry for the confusion!

2022-06-28 10:44 UTC, bvenn approved these changes

2022-06-29 10:42 UTC, merged